name: Phoebus build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build
      run: mvn -Dgpg.skip=true --batch-mode install
    - name: Publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -Dgpg.skip=true --batch-mode -DskipTests deploy
      if: ${{ github.repository == 'ControlSystemStudio/phoebus' && (github.ref == 'refs/heads/master' || github.ref == 'refs/tags/*') }}

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@2.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: phoebus-product/target/product-4.6.6-SNAPSHOT.zip
        asset_name: Commander_v0.1.0-SNAPSHOT-nightly-linux-x86_64.zip
        tag: Commander-nightly-build
        overwrite: true
        body: "Latest and greatest nightly build. This is NOT a stable version."
