name: Linux Nightly

on: [push]

jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
#    - run: |
#        git fetch --prune --unshallow --tags

    - name: Install dependencies
      run: |
        sudo apt install -y protobuf-compiler
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build
      run: mvn -Djavafx.platform=linux -DskipTests -T6 verify

#    - name: Tag Repo
#      uses: richardsimko/update-tag@v1
#      with:
#        tag_name: commander-0.1.0
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete old release assets
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ github.token }}
        tag: commander-0.1.0 # This may also be of the form 'refs/tags/staging'
        assets: '*nightly-linux-x86_64.zip'
        fail-if-no-release: false
        fail-if-no-assets: false

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@2.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: phoebus-product/target/product-4.6.6-SNAPSHOT.zip
        asset_name: commander-0.1.0-linux-x86_64.zip
        tag: commander-0.1.0
        overwrite: true
        body: "Latest and greatest nightly build. This is NOT a stable version."

